//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQA
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string sName { get; set; }
        public string sPhone { get; set; }
        public string sRole { get; set; }
    }
}
