//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMain
    {
        public int MainID { get; set; }
        public Nullable<System.DateTime> aDate { get; set; }
        public string aTime { get; set; }
        public string TableName { get; set; }
        public string WaiterName { get; set; }
        public string status { get; set; }
        public string orderType { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> received { get; set; }
        public Nullable<double> change { get; set; }
        public Nullable<int> driverID { get; set; }
        public string custName { get; set; }
        public string custPhone { get; set; }
    }
}
